### PR TITLE
Technical direction

### PR DESCRIPTION
**Pull request by eirikurn**
Digital Iceland has asked me to publish the Technical Discipline to the handbook where it should live and evolve.

To fit with other handbook material, I translated it to English and updated some of the text to better match our work and changes that have been made since the first draft.

This is a document that we all own together, so I appreciate any input on its structure and content, now and in the future.

For reference, here is the original draft:

https://samradsgatt.island.is/oll-mal/$Cases/Details/?id=1536

### CODE REVIEW

**Review by andri-fjr — APPROVED** [review]

**Review by saevarma — APPROVED** [review]
Lítur vel út. Lagaði nokkrar typos sem ég fann.

**Comment by pshomov** [comment]
Really good document ❤️

**Review by arividar — APPROVED** [review]
Really good.

**Review by jonatanarnar — COMMENTED** [review]
Glæsilegt að fá hingað!

**Pull request merged**
